name: persomsg
main: me.clearrelic24.crplugins.crplugins
version: 1.0.0
description: CR24 STUDIO 
author: CR24Studio
commands:
   forum:
     description: Set yourself on fire.
     aliases: [forum, ForumLink]
     permission: persomsg.forum
   ytb:
     description: Set yourself on fire.
     aliases: [youtube, Chaine]
     permission: persomsg.ytb
   website:
     description: Set yourself on fire.
     aliases: [website, web, site]
     permission: persomsg.website
   map:
     description: Set yourself on fire.
     aliases: [map, mapsite]
     permission: persomsg.map    